### ISSUE TITLE
[Bug]Crash on Startup

### ISSUE THREAD

**Issue by yukiedarling13** [AlexanderLaptev/wallpaper-craft#1]
MC version: 1.12.2
Forge version: 14.23.5.2847  
Mod version: 1.0.0-alpha+

The mod crashes on startup. Even by itself. I also tried adding chisel because its listed as a dependency?
[crash-2019-11-22_17.04.27-client.txt](https://github.com/AlexanderLaptev/wallpaper-craft/files/3881624/crash-2019-11-22_17.04.27-client.txt)

**Comment by ElueeSS** [comment]
I have the same issue, tried vanilla and tried with a variety of mods that I usually use, both ending up in a crash. Really like the look of this mod!

https://paste.dimdev.org/opalowisuj.mccrash

**Comment by AlexanderLaptev** [comment]
The issue is being worked on. Thank you for reporting it!
