### ISSUE TITLE
Stairs and Slabs, plus Issue with Recipes

### ISSUE THREAD

**Issue by GRini249** [AlexanderLaptev/wallpaper-craft#3]
Hello, I'm using the 1.15.1 version of your mod. I noticed I'm not able to access the recipes for blocks other than Solid White Gray and the presses. I also can't create the colors the way described. 

Beyond that, I was thinking this mod would be incredible with the addition of stairs, slabs, and the other additional forms of blocks or if they could be modified with a stonecutter. 

Thank you so much,
Gianna

**Comment by AlexanderLaptev** [comment]
Hello! Unfortunately, we are not connected with the development of all versions later than for MC 1.12.2. You should consider contacting their authors. As for 1.12.2 version, slabs and stairs can be created with mods such as Blockcraftery or ArchitectureCraft. Glass panes for 1.12.2 are added as a long-term task.
