### ISSUE TITLE
I tried to enter my world and I crashed (again)

### ISSUE THREAD

**Issue by erpad** [AlexanderLaptev/wallpaper-craft#4]
I have a bunch of other mods but wallpapercraft was the only mod listed on the list of mods could have been a cause of the crash. 

https://paste.dimdev.org/oyavagexuj.mccrash

**Comment by AlexanderLaptev** [comment]
How did you get that piece of colored paste? Crafting, JEI or "give" command? It seems like you've got a piece of paste with invalid metadata which should be impossible to get via crafting.
