### ISSUE TITLE
I found textureless block which crashes the game if you place it.

### ISSUE THREAD

**Issue by SpiderKolo** [AlexanderLaptev/wallpaper-craft#5]
So I found this weird block which when you place instantly crash your game.

You can find it when you scroll down from "Larch Honeycomb". If you scroll from that block with no texture, you always will scroll into "Zebrawood Honeycomb" (doesn't matter if you scroll upwards or downwards).

![2020-03-25_07 51 47](https://user-images.githubusercontent.com/62638498/77509762-9d6edb00-6e6d-11ea-92b8-8f75948a6114.png)

I made here three horizontal "lines" or "rows" of blocks. Blocks above 5th slot in hotbar are blocks you would scroll from.
Blocks on left are blocks you get if you scroll one by one downwards.
Blocks on right are blocks you get if you scroll one by one upwards.
Notice how you may find this block when you scroll downwards, but not upwards.

Here few extra screenshots where we see blocks ID's and their description just to clarify which specific block I meant:

![2020-03-25_07 51 56](https://user-images.githubusercontent.com/62638498/77509765-9e077180-6e6d-11ea-958f-cfc0fff0994e.png)
![2020-03-25_07 52 01](https://user-images.githubusercontent.com/62638498/77509767-9f389e80-6e6d-11ea-8c6c-0b3b23fa0906.png)
![2020-03-25_07 52 05](https://user-images.githubusercontent.com/62638498/77509770-9fd13500-6e6d-11ea-81f5-95850e7b7fe2.png)

I don't know if there are more blocks like those, this is the first one I found.

Few more informations:
Version of game: 1.12.2
Version of mod: 1.0.1 alpha

I'm making modpack around mod "Cubic Chunks" if that somehow helps, but I don't think it would affect this mod in any way.

If you put that block into Chisel, you won't find:

![2020-03-25_08 03 44](https://user-images.githubusercontent.com/62638498/77510487-39e5ad00-6e6f-11ea-853d-c66bf5a7f64b.png)

But other blocks appear to have no issues with Chisel:

![2020-03-25_08 03 57](https://user-images.githubusercontent.com/62638498/77510492-3b16da00-6e6f-11ea-92cb-359b9b4293c8.png)

![2020-03-25_08 04 05](https://user-images.githubusercontent.com/62638498/77510495-3baf7080-6e6f-11ea-8166-13e560e7398b.png)

**Comment by AlexanderLaptev** [comment]
Could you please provide any crashlog?

**Comment by AlexanderLaptev** [comment]
Not needed now, I was able to reproduce the issue. It seems like a very simple bug with scrolling.
