### ISSUE TITLE
The world with this mod crashes with java.nio.channels.closedchannelexception

### ISSUE THREAD

**Issue by EnchGA** [AlexanderLaptev/wallpaper-craft#6]
When i start new game, the world crashes with java.nio.channels.closedchannelexception and it throws me in multiplayer servers list. When i launch the same world without this mod it works perfectly. I allocated 6-8 GB of RAM because i thought maybe this will work, but no...

**Comment by AlexanderLaptev** [comment]
Could you please provide a crashlog file?

**Comment by AlexanderLaptev** [comment]
Closed due to inactivity.
