### ISSUE TITLE
[Bug] Shift + Scroll Not Working At All

### ISSUE THREAD

**Issue by Jayziken** [AlexanderLaptev/wallpaper-craft#7]
**Describe the bug**
I cannot shift+scroll when crafting. I place the paste, then press and the block which works fine, but scrolling between the colour options simply doesn't work. I've tried changing the keybind so it's not double-bound but no luck. What would cause this feature not to work? If you're meant to do it whilst holding the block, that doesn't work either. 

**To Reproduce**
I have a modded 1.12.2 SMP server, these are all of the mods currently installed, in case it's a compatibility issue: https://imgur.com/a/MLFVc56 What would cause the scroll feature to not work? 

**Expected behavior**
No matter the keybind, the scrolling doesn't work. I don't know if you're meant to scroll before or after crafting the block. Or if it's meant to be in your hand but it doesn't work in any cases. I'm assuming it shouldn't be hard to find out how to scroll between options if it was working properly. 

**Screenshots**
Crafting table view: https://imgur.com/a/yuxBPPu
Key bind: https://imgur.com/a/Wjml58R

**Environment information:**
 - OS: Windows 10 64
 - Minecraft version: 1.12.2
 - Forge version: Forge 14.23.5.2847

**Comment by AlexanderLaptev** [comment]
Closed due to inactivity.
